export interface Student {
    name: string,
    last_name: string,
    gender: string,
    street: string,
    neighborhood: string,
    city: string,
    zip_code: string,
    number: string,
    SchoolId: number,
    age: string,
    complement: string,
    turn:string,
    UserId: number,
    price: string,
    image: string,
    latitude: string,
    longitude: string,
}
